spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/university_db
        username: user
        password: 12345678
    data:
        web:
            pageable:
                max-page-size: 15
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect

server:
    error:
        include-message: always

university:
    max-group-size: 30
    lesson-duration: PT1H20M