spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/university_db
        password: 12345678
        username: user
    data:
        web:
            pageable:
                max-page-size: 15
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect

group:
    size: 30
timeframe:
    duration: PT1H20M
