INSERT INTO courses (name) VALUES ('Law');
INSERT INTO courses (name) VALUES ('Biology');
INSERT INTO courses (name) VALUES ('Music');
INSERT INTO rooms (name, capacity) VALUES ('A111', 30);
INSERT INTO rooms (name, capacity) VALUES ('B222', 30);
INSERT INTO rooms (name, capacity) VALUES ('C333', 30);
INSERT INTO rooms (name, capacity) VALUES ('D444', 30);
INSERT INTO courses_rooms (course_id, room_id) VALUES (1, 1);
INSERT INTO courses_rooms (course_id, room_id) VALUES (1, 2);
INSERT INTO courses_rooms (course_id, room_id) VALUES (1, 3);