INSERT INTO groups (name) VALUES ('AA-11');
INSERT INTO groups (name) VALUES ('BB-22');
INSERT INTO groups (name) VALUES ('CC-33');
INSERT INTO groups (name) VALUES ('DD-44');
INSERT INTO students (group_id, name, surname, birth_date, gender) VALUES (1, 'Anna', 'Dvorecka', '2001-01-01', 'FEMALE');
INSERT INTO students (group_id, name, surname, birth_date, gender) VALUES (2, 'Sergii', 'Koklush', '2002-02-02', 'MALE');
INSERT INTO students (group_id, name, surname, birth_date, gender) VALUES (null, 'Vladislav', 'Ostrovski', '2003-03-03', 'MALE');
INSERT INTO teachers (name, surname, email, birth_date, gender) VALUES ('Victor', 'Doncov', 'doncov@gmail.com', '1991-01-01', 'MALE');
INSERT INTO teachers (name, surname, email, birth_date, gender) VALUES ('Aleksandra', 'Ivanova', 'ivanova@ukr.net', '1992-02-02', 'FEMALE');
INSERT INTO teachers (name, surname, email, birth_date, gender) VALUES ('Anatoly', 'Sviridov', 'sviridov@gmail.com', '1993-03-03', 'MALE');
INSERT INTO teachers (name, surname, email, birth_date, gender) VALUES ('Roman', 'Tarachkov', 'tarachkov@gmail.com', '1988-03-03', 'MALE');
INSERT INTO timeframes (sequence, start_time, end_time) VALUES (1, '08:00', '09:20');
INSERT INTO timeframes (sequence, start_time, end_time) VALUES (2, '09:40', '11:00');
INSERT INTO timeframes (sequence, start_time, end_time) VALUES (3, '11:20', '12:40');
INSERT INTO timeframes (sequence, start_time, end_time) VALUES (4, '13:00', '14:20');
INSERT INTO courses (name) VALUES ('Law');
INSERT INTO courses (name) VALUES ('Biology');
INSERT INTO courses (name) VALUES ('Music');
INSERT INTO courses (name) VALUES ('Accounting');
INSERT INTO rooms (name, capacity) VALUES ('A111', 30);
INSERT INTO rooms (name, capacity) VALUES ('B222', 30);
INSERT INTO rooms (name, capacity) VALUES ('C333', 30);
INSERT INTO rooms (name, capacity) VALUES ('D444', 30);
INSERT INTO lessons (date, timeframe_id, course_id, teacher_id, room_id) VALUES ('2020-12-12', 1, 1, 1, 1);
INSERT INTO lessons (date, timeframe_id, course_id, teacher_id, room_id) VALUES ('2020-12-13', 2, 2, 2, 2);
INSERT INTO lessons (date, timeframe_id, course_id, teacher_id, room_id) VALUES ('2020-12-14', 3, 3, 3, 3);
INSERT INTO lessons_groups (lesson_id, group_id) VALUES (1, 1);
INSERT INTO lessons_groups (lesson_id, group_id) VALUES (1, 2);
INSERT INTO lessons_groups (lesson_id, group_id) VALUES (2, 1);
INSERT INTO lessons_groups (lesson_id, group_id) VALUES (2, 2);
INSERT INTO courses_rooms (course_id, room_id) VALUES (1, 1);
INSERT INTO courses_rooms (course_id, room_id) VALUES (1, 2);
INSERT INTO courses_rooms (course_id, room_id) VALUES (2, 2);
INSERT INTO courses_rooms (course_id, room_id) VALUES (2, 3);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 3);
INSERT INTO teachers_courses (teacher_id, course_id) VALUES (1, 1);
INSERT INTO teachers_courses (teacher_id, course_id) VALUES (1, 2);
INSERT INTO teachers_courses (teacher_id, course_id) VALUES (2, 2);
INSERT INTO teachers_courses (teacher_id, course_id) VALUES (2, 3);