INSERT INTO groups (name) VALUES ('AA-11');
INSERT INTO groups (name) VALUES ('BB-22');
INSERT INTO groups (name) VALUES ('CC-33');
INSERT INTO courses (name) VALUES ('Law');
INSERT INTO courses (name) VALUES ('Biology');
INSERT INTO courses (name) VALUES ('Music');
INSERT INTO courses (name) VALUES ('Art');
INSERT INTO students (group_id, name, surname, birth_date, gender) VALUES (1, 'Anna', 'Dvorecka', '2001-01-01', 'FEMALE');
INSERT INTO students (group_id, name, surname, birth_date, gender) VALUES (2, 'Sergii', 'Koklush', '2002-02-02', 'MALE');
INSERT INTO students (group_id, name, surname, birth_date, gender) VALUES (null, 'Vladislav', 'Ostrovski', '2003-03-03', 'MALE');
INSERT INTO students_courses (student_id, course_id) VALUES (1, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 3);