INSERT INTO groups (group_name) VALUES ('AA-11');
INSERT INTO groups (group_name) VALUES ('BB-22');
INSERT INTO groups (group_name) VALUES ('CC-33');
INSERT INTO teachers (teacher_name, teacher_surname, teacher_birthdate, teacher_gender) VALUES ('Victor', 'Doncov', '1991-01-01', 'MALE');
INSERT INTO teachers (teacher_name, teacher_surname, teacher_birthdate, teacher_gender) VALUES ('Aleksandra', 'Ivanova', '1992-02-02', 'FEMALE');
INSERT INTO teachers (teacher_name, teacher_surname, teacher_birthdate, teacher_gender) VALUES ('Anatoly', 'Sviridov', '1993-03-03', 'MALE');
INSERT INTO timeframes (timeframe_sequance, start_time, end_time) VALUES (1, '08:00', '09:20');
INSERT INTO timeframes (timeframe_sequance, start_time, end_time) VALUES (2, '09:40', '11:00');
INSERT INTO timeframes (timeframe_sequance, start_time, end_time) VALUES (3, '11:20', '12:40');
INSERT INTO courses (course_name) VALUES ('Law');
INSERT INTO courses (course_name) VALUES ('Biology');
INSERT INTO courses (course_name) VALUES ('Music');
INSERT INTO rooms (room_name, room_capacity) VALUES ('A111', 30);
INSERT INTO rooms (room_name, room_capacity) VALUES ('B222', 30);
INSERT INTO rooms (room_name, room_capacity) VALUES ('C333', 30);
INSERT INTO lessons (lesson_date, timeframe_id, course_id, teacher_id, room_id) VALUES ('2020-12-12', 1, 1, 1, 1);
INSERT INTO lessons (lesson_date, timeframe_id, course_id, teacher_id, room_id) VALUES ('2020-12-12', 2, 2, 2, 2);
INSERT INTO lessons (lesson_date, timeframe_id, course_id, teacher_id, room_id) VALUES ('2020-12-12', 3, 3, 3, 3);