INSERT INTO teachers (name, surname, birth_date, gender) VALUES ('Victor', 'Doncov', '1991-01-01', 'MALE');
INSERT INTO teachers (name, surname, birth_date, gender) VALUES ('Aleksandra', 'Ivanova', '1992-02-02', 'FEMALE');
INSERT INTO teachers (name, surname, birth_date, gender) VALUES ('Anatoly', 'Sviridov', '1993-03-03', 'MALE');
INSERT INTO timeframes (sequence, start_time, end_time) VALUES (1, '08:00', '09:20');
INSERT INTO timeframes (sequence, start_time, end_time) VALUES (2, '09:40', '11:00');
INSERT INTO timeframes (sequence, start_time, end_time) VALUES (3, '11:20', '12:40');
INSERT INTO courses (name) VALUES ('Law');
INSERT INTO courses (name) VALUES ('Biology');
INSERT INTO courses (name) VALUES ('Music');
INSERT INTO rooms (name, capacity) VALUES ('A111', 30);
INSERT INTO rooms (name, capacity) VALUES ('B222', 30);
INSERT INTO rooms (name, capacity) VALUES ('C333', 30);
INSERT INTO groups (name) VALUES ('AA-11');
INSERT INTO groups (name) VALUES ('BB-22');
INSERT INTO groups (name) VALUES ('CC-33');